spring:
  application:
    name: ForoHub

  datasource:
    url: jdbc:mysql://localhost:3306/forohub
    username: alura_user
    password: alura_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

api:
  security:
    secret: ${JWT_SECRET:123456}

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
